### ISSUE TITLE
Fails to run jbang --edit

### ISSUE THREAD

**Issue by fbricon** [maxandersen/jbang#13]
I can run a chmod+x'ed Hello.java file from a terminal, but when trying to generate a build file to open it in my IDE, it fails with an exception:

```
➜  jbang java -version
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment Zulu13.27+9-CA (build 13+33)
OpenJDK 64-Bit Server VM Zulu13.27+9-CA (build 13+33, mixed mode, sharing)
➜  jbang ./Hello.java             
0 [main] INFO Hello  - Welcome to jbang
2 [main] INFO Hello  - Hello from Java!
➜  jbang jbang --edit Hello.java
dk.xam.jbang.ExitException
        at dk.xam.jbang.Main.quit(Main.java:75)
        at dk.xam.jbang.Main.call(Main.java:119)
        at dk.xam.jbang.Main.call(Main.java:27)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at dk.xam.jbang.Main.main(Main.java:79)
/Users/fbricon/.jbang/temp_projects/jbang_tmp_project__Hello.java_8726bd513b68378f53ba944e3c15ddb0966e9e41eabbf79e6b58270055699479
```

The source file, Hello.java :

```java
//usr/bin/env jbang "$0" "$@" ; exit $?

//DEPS log4j:log4j:1.2.17 

import static java.lang.System.out;

import org.apache.log4j.Logger;
import org.apache.log4j.BasicConfigurator;

import java.util.Arrays;

class Hello {

	static final Logger logger = Logger.getLogger(Hello.class);

	public static void main(String[] args) {
		BasicConfigurator.configure(); 
		logger.info("Welcome to jbang");

		Arrays.asList(args).forEach(arg -> logger.warn("arg: " + arg));
		logger.info("Hello from Java!");
	}
}
```

**Comment by maxandersen** [comment]
fixed in commit #0abb947a9fc208c4ea1967459a9ef2b75825c58d so try out v0.2.1+ please
