### ISSUE TITLE
enable launch of javafx

### ISSUE THREAD

**Issue by maxandersen** [maxandersen/jbang#19]
JavaFX is tricky or maybe its just very picky ;)

```
jbang https://raw.githubusercontent.com/maxandersen/jbang/master/examples/jfxarc.java

Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: jfxarc
	at javafx.application.Application.launch(Application.java:304)
	at jfxarc.main(jfxarc.java:43)
Caused by: java.lang.ClassNotFoundException: jfxarc
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
```

Need to see if in the special case of jfx if we can do some transformation in jbang to make it happy at launch time.

**Comment by maxandersen** [comment]
following https://openjfx.io/openjfx-docs/#install-javafx I could only make it work if I compiled the classes first, launch directly with java seem to not work.

And even then I had to manually download jfx libs and put in separate dir. Would be nicer if there was a jdk with a well-known location or default installed jfx.

**Comment by tomsontom** [comment]
i'll see if i can put some of my OSS-Time on it

**Comment by maxandersen** [comment]
that would be awesome @tomsontom !

**Comment by maxandersen** [comment]
this been possible for a while now!
