### ISSUE TITLE
jbang should display a proper error message when older jdk version are used.

### ISSUE THREAD

**Issue by iocanel** [maxandersen/jbang#25]
I am currently getting this error message when using jbang with jdk8.
    
    Error: A JNI error has occurred, please check your installation and try again
    Exception in thread "main" java.lang.UnsupportedClassVersionError: 
    dk/xam/jbang/Main has been compiled by a more recent version of the Java Runtime 
    (class file version 55.0), this version of the Java Runtime only recognizes class file 
    versions up to 52.0
    	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

The jbang script should detect that and display a proper error message.

**Comment by maxandersen** [comment]
agreed - I started on that but then realized might as well just support java8 :) #20 #23
