### ISSUE TITLE
HTTP 301 not supported

### ISSUE THREAD

**Issue by quintesse** [maxandersen/jbang#75]
Getting the following exception when a server returns a 301 Moved Permanently:

```
[jbang] Could not download http://gitlab.cee.redhat.com/blah/blah/blah/Foo.java
dk.xam.jbang.ExitException: Could not download http://gitlab.cee.redhat.com/blah/blah/blah/Foo.java
	at dk.xam.jbang.Main.fetchFromURL(Main.java:830)
	at dk.xam.jbang.Main.prepareScript(Main.java:757)
	at dk.xam.jbang.Main.doCall(Main.java:236)
	at dk.xam.jbang.Main.call(Main.java:254)
	at dk.xam.jbang.Main.call(Main.java:35)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at dk.xam.jbang.Main.main(Main.java:121)
Caused by: java.io.FileNotFoundException: No file to download. Server replied HTTP code: 301
	at dk.xam.jbang.Util.downloadFile(Util.java:105)
	at dk.xam.jbang.Main.fetchFromURL(Main.java:826)
	... 12 more
```

(Sanitized URL because it's from the corporate network. Ask me in private if you need it to reproduce)

**Comment by maxandersen** [comment]
ah, so just a matter of honoring redirects ? got a patch ? )

**Comment by quintesse** [comment]
Here you are :-)

Btw I also added a PR for trusting SSL certificates. In my case the redirect was from the http:// or to the https:// which then used an unknown certificate so it still failed. I needed to option added by that second PR to make everything work for me.
